version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  proxy:
    image: redis-proxy
    container_name: proxy
    ports:
      - 3000:3000
    links:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://cache
      - PROXY_PORT=3000
      - CACHE_EXPIRY=7200000
      - CACHE_CAPACITY=10
