version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  proxy:
    image: redis-proxy
    ports:
      - ${PORT}:${PORT}
    links:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT}
      - CACHE_EXPIRY=${CACHE_EXPIRY}
      - CACHE_CAPACITY=${CACHE_CAPACITY}
